### ISSUE TITLE
route import error message doesn't clear when i repeat import with the correct format

### ISSUE THREAD

**Issue by badpens** [jsnyders/ClimbingComp#2]
git pull of jsnyders/ClimbingComp

tried import routes with wrong .csv -- got error (as expected):

Error 
Failed to upload routes
Missing route location on line 52 Missing route color on line 52 Bad route number on line 52 Bad points on line 52 
500 Internal Server Error

then clicked "choose file" to select correct file, and "upload".  upload seems to have worked, but error message still appears.

would be good to have a "route import done" message.  (msg even if no error before sucessful import)

**Comment by badpens** [comment]
note: i know that i could dismiss the message by clicking the (X), but after a successful import, the message should automagically go away, as it is misleading.

**Comment by jsnyders** [comment]
fixed
