### ISSUE TITLE
Failed to upload climbers

### ISSUE THREAD

**Issue by badpens** [jsnyders/ClimbingComp#3]
Error 
Failed to upload climbers
undefined is not a function
500 Internal Server Error

all the import stats were blank

however, it appears quite a few of the climbers (seems like 1137 climbers) imported ok.

20150227.import_fail.test.climbers.csv  (in Dropbox\snyders_ornes_shared\ClimbingComp_issues)

in the gui i changed the columns to:
     member#, firstname, lastname, birthday, gender, category, team, region

**Comment by jsnyders** [comment]
This is fixed along with a number of other errors in import error handling.

**Comment by badpens** [comment]
With the latest, now I get a (mostly) black page after import seems to have completed.

(top-centered) :       Import Climber Results   (on a light gray background)

(most of the page blank)

(bottom)   ClimbingComp _About_                          tmadmin    | XYZ test comp 2015-3-1

**Comment by badpens** [comment]
(how do i re-open this issue?)

**Comment by jsnyders** [comment]
best to create a new issue. I can't reproduce the problem you describe.
