### ISSUE TITLE
Import takes too long. Was: Import Climbers doesn't provide status/results

### ISSUE THREAD

**Issue by badpens** [jsnyders/ClimbingComp#7]
(related to issue #3)

With latest (just pulled 10 mins ago), I tried to import ~2900 climbers.  For the first several minutes, the browser/page showed a spinning activity indicator.  The spinning then stopped, and all I saw was:

(top-centered) : Import Climber Results (on a light gray background)

(most of the page blank)

(bottom) ClimbingComp About tmadmin | XYZ test comp 2015-3-1

However, I used mysqldump on the server and found that the import was still happening.  In fact it was only about 66% done.

My import (going over the internet) was running at about 6 or 7 climbers added per second, leading to about 7 minutes for the import.

Is there some sort of timeout (maybe 5 minutes) in the activity indicator UI thing?    something else?

**Comment by badpens** [comment]
i cleared the DB, and ran the test again. 
the "importing. please wait..." and spinning indicator went away after 4 minutes.

the first time i repeated the test, i noticed that it went away at about 4 minutes, but wasn't paying attention to know when exactly it happened.  i repeated it again, and it was exactly at the 4 minute mark.  also at ~1660 climbers out of ~2984.

is there a UI timeout at 4min?

also, is there any way to have an indication of how far along the import is progressing?
a "% complete" so far?
or a "# of records imported" so far?

**Comment by jsnyders** [comment]
I must be running on faster hardware. I import 2984 climbers in 43sec.
Progress is a little tricky to do.
a) I can look at improving import code to see if I can make it faster.
b) If needed the import can be turned into a "job" where you import and the server works on it and you can see an outstanding job and come back later to find out the results. But I hope it doesn't come to that.

**Comment by badpens** [comment]
Any idea if the 4min timeout can be extended?

**Comment by jsnyders** [comment]
The timeout is most likely related to browser or other network infra that is beyond the control of the node app. 

I reworked the import code to do bulk inserts and it is now much faster. For me the time went from 43sec to less than 300ms for the same input file.

**Comment by badpens** [comment]
Great.  Let me know when this new change is checked in.

**Comment by jsnyders** [comment]
the performance improvement seems to work well and is stable after a bunch of testing so closing now
